version: '3'

services:
  postgres-local:
    image: 'postgres'
    ports:
      - '5432:5432'
    container_name: my-postgres-local
    volumes:
      - 'C:\DockerVolumes\POSTGRES:/var/lib/postgresql/data'
    environment:
       - POSTGRES_PASSWORD=test